#!/bin/bash

# Improved SSH Hardening Script
# Handles different server configurations and SSH service names

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging
LOG_FILE="/var/log/ssh_hardening_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$LOG_FILE")
exec 2>&1

echo -e "${BLUE}=== Improved SSH Security Hardening Script ===${NC}"
echo -e "${BLUE}Started at: $(date)${NC}"
echo -e "${BLUE}Log file: $LOG_FILE${NC}"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}This script must be run as root${NC}"
   exit 1
fi

# Backup original SSH config
echo -e "${YELLOW}Creating backup of original SSH configuration...${NC}"
if [ -f /etc/ssh/sshd_config ]; then
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d_%H%M%S)
fi

# Function to detect SSH service name
detect_ssh_service() {
    if systemctl list-units --type=service | grep -q "sshd.service"; then
        echo "sshd"
    elif systemctl list-units --type=service | grep -q "ssh.service"; then
        echo "ssh"
    else
        echo "ssh"  # Default fallback
    fi
}

# Function to apply SSH hardening rules (compatible version)
apply_ssh_hardening() {
    echo -e "${GREEN}Applying SSH hardening rules...${NC}"

    # Detect SSH version capabilities
    SSH_VERSION=$(sshd -V 2>&1 | head -n1 | grep -oP 'OpenSSH_\K[0-9]+\.[0-9]+' || echo "7.0")

    # Create hardened SSH config with compatibility
    cat > /etc/ssh/sshd_config << EOF
# SSH Hardening Configuration
# Generated by Improved SSH Security Hardening Script
# SSH Version: $SSH_VERSION

# Basic SSH Settings
Port 22
Protocol 2

# Authentication Security
PermitRootLogin no
PermitEmptyPasswords no
PasswordAuthentication yes  # Will be disabled after key setup
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys

# Security Settings
MaxAuthTries 3
MaxSessions 10
LoginGraceTime 60
ClientAliveInterval 300
ClientAliveCountMax 2
Banner /etc/ssh/banner

# Cryptographic Settings (compatible)
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Compatible cipher configurations
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256
Ciphers aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-256,hmac-sha2-512,umac-128@openssh.com

# Logging
LogLevel VERBOSE
SyslogFacility AUTH

# Access Control
AllowTcpForwarding no
X11Forwarding no
AllowAgentForwarding no
PermitTunnel no
PermitOpen none

# Subsystem Configuration
Subsystem sftp /usr/lib/openssh/sftp-server

# UsePAM
UsePAM yes

# Security Enhancements
StrictModes yes
Compression no
TCPKeepAlive yes
UseDNS no

# Only include if supported by SSH version
EOF

    # Add UsePrivilegeSeparation only for older SSH versions
    if [[ $(echo "$SSH_VERSION < 7.6" | bc -l 2>/dev/null || echo "0") == "1" ]]; then
        echo "UsePrivilegeSeparation yes" >> /etc/ssh/sshd_config
    fi

    chmod 644 /etc/ssh/sshd_config
    chown root:root /etc/ssh/sshd_config
}

# Function to create SSH banner
create_ssh_banner() {
    echo -e "${GREEN}Creating SSH banner...${NC}"

    cat > /etc/ssh/banner << 'EOF'
***************************************************************************
                            AUTHORIZED ACCESS ONLY
***************************************************************************

This system is for authorized users only. Individual use of this system
and/or network without authority from the system owner is strictly
prohibited.

Unauthorized access is a violation of state and federal, civil and criminal
laws. All activities on this system are monitored and logged.

***************************************************************************
                IMMEDIATE NOTIFICATION WILL BE SENT TO
              SYSTEM ADMINISTRATORS FOR VIOLATIONS
***************************************************************************
EOF

    chmod 644 /etc/ssh/banner
    chown root:root /etc/ssh/banner
}

# Function to secure SSH host keys
secure_host_keys() {
    echo -e "${GREEN}Securing SSH host keys...${NC}"

    # Backup existing host keys
    if [ -d /etc/ssh ]; then
        find /etc/ssh -name "ssh_host_*_key*" -exec cp {} {}.backup \; 2>/dev/null || true
    fi

    # Regenerate host keys with stronger algorithms
    rm -f /etc/ssh/ssh_host_*_key*

    ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" -C "$(hostname)-ed25519" 2>/dev/null || true
    ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N "" -C "$(hostname)-rsa" 2>/dev/null || true
    ssh-keygen -t ecdsa -b 521 -f /etc/ssh/ssh_host_ecdsa_key -N "" -C "$(hostname)-ecdsa" 2>/dev/null || true

    # Set proper permissions
    chmod 600 /etc/ssh/ssh_host_*_key 2>/dev/null || true
    chmod 644 /etc/ssh/ssh_host_*_key.pub 2>/dev/null || true
    chown root:root /etc/ssh/ssh_host_* 2>/dev/null || true
}

# Function to configure fail2ban
configure_fail2ban() {
    echo -e "${GREEN}Configuring fail2ban for SSH...${NC}"

    # Check if fail2ban is installed
    if command -v fail2ban-server &> /dev/null; then
        echo -e "${GREEN}fail2ban already installed${NC}"
    else
        echo -e "${YELLOW}Installing fail2ban...${NC}"
        # Install without interactive prompts
        DEBIAN_FRONTEND=noninteractive apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y fail2ban
    fi

    # Create fail2ban SSH configuration
    cat > /etc/fail2ban/jail.local << 'EOF'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3
backend = systemd

[sshd]
enabled = true
port = 22
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
EOF

    # Restart and enable fail2ban
    systemctl restart fail2ban 2>/dev/null || systemctl start fail2ban 2>/dev/null || true
    systemctl enable fail2ban 2>/dev/null || true
}

# Function to configure firewall (UFW or iptables)
configure_firewall() {
    echo -e "${GREEN}Configuring firewall...${NC}"

    if command -v ufw &> /dev/null; then
        configure_ufw
    else
        echo -e "${YELLOW}UFW not found, installing...${NC}"
        DEBIAN_FRONTEND=noninteractive apt-get install -y ufw
        configure_ufw
    fi
}

# Function to configure UFW
configure_ufw() {
    echo -e "${GREEN}Configuring UFW firewall...${NC}"

    # Reset UFW
    ufw --force reset 2>/dev/null || true

    # Default policies
    ufw default deny incoming 2>/dev/null || true
    ufw default allow outgoing 2>/dev/null || true

    # Allow SSH from common subnets
    ufw allow from 192.168.1.0/24 to any port 22 2>/dev/null || true
    ufw allow from 192.168.2.0/24 to any port 22 2>/dev/null || true
    ufw allow from 10.0.0.0/8 to any port 22 2>/dev/null || true

    # Enable UFW
    ufw --force enable 2>/dev/null || true
}

# Function to create security monitoring script
create_monitoring_script() {
    echo -e "${GREEN}Creating security monitoring script...${NC}"

    cat > /usr/local/bin/ssh_security_monitor.sh << 'EOF'
#!/bin/bash

# SSH Security Monitoring Script
# Monitors SSH access and sends alerts

LOG_FILE="/var/log/auth.log"
ALERT_THRESHOLD=5
TIME_WINDOW=300  # 5 minutes

# Count failed SSH attempts in the time window
FAILED_ATTEMPTS=$(journalctl -u ssh --since "5 minutes ago" 2>/dev/null | grep -c "Failed password" || echo 0)

if [ "$FAILED_ATTEMPTS" -ge "$ALERT_THRESHOLD" ]; then
    echo "SECURITY ALERT: $FAILED_ATTEMPTS failed SSH attempts detected in the last 5 minutes" | \
    logger -t SSH_SECURITY_MONITOR -p auth.warning
fi

# Check for root login attempts
ROOT_ATTEMPTS=$(journalctl -u ssh --since "5 minutes ago" 2>/dev/null | grep -c "root.*Accepted" || echo 0)
if [ "$ROOT_ATTEMPTS" -gt 0 ]; then
    echo "SECURITY ALERT: Root login attempt detected" | \
    logger -t SSH_SECURITY_MONITOR -p auth.warning
fi
EOF

    chmod +x /usr/local/bin/ssh_security_monitor.sh

    # Add to crontab
    (crontab -l 2>/dev/null; echo "*/5 * * * * /usr/local/bin/ssh_security_monitor.sh") | crontab - || true
}

# Function to test SSH configuration
test_ssh_config() {
    echo -e "${GREEN}Testing SSH configuration...${NC}"

    if sshd -t 2>/dev/null; then
        echo -e "${GREEN}SSH configuration test passed${NC}"
        return 0
    else
        echo -e "${RED}SSH configuration test failed${NC}"
        sshd -t
        return 1
    fi
}

# Function to restart SSH service
restart_ssh_service() {
    echo -e "${GREEN}Restarting SSH service...${NC}"

    SSH_SERVICE=$(detect_ssh_service)
    echo -e "${BLUE}Detected SSH service: $SSH_SERVICE${NC}"

    systemctl restart "$SSH_SERVICE"

    if systemctl is-active --quiet "$SSH_SERVICE"; then
        echo -e "${GREEN}SSH service restarted successfully${NC}"
        return 0
    else
        echo -e "${RED}Failed to restart SSH service${NC}"
        systemctl status "$SSH_SERVICE"
        return 1
    fi
}

# Function to create security audit report
create_audit_report() {
    echo -e "${GREEN}Creating security audit report...${NC}"

    REPORT_FILE="/var/log/ssh_security_audit_$(date +%Y%m%d_%H%M%S).txt"

    cat > "$REPORT_FILE" << EOF
=== SSH Security Audit Report ===
Server: $(hostname)
Date: $(date)
IP Address: $(hostname -I | awk '{print $1}')

SSH Configuration:
- Protocol: $(grep '^Protocol' /etc/ssh/sshd_config 2>/dev/null || echo "Not found")
- Port: $(grep '^Port' /etc/ssh/sshd_config 2>/dev/null || echo "Not found")
- Root Login: $(grep '^PermitRootLogin' /etc/ssh/sshd_config 2>/dev/null || echo "Not found")
- Password Auth: $(grep '^PasswordAuthentication' /etc/ssh/sshd_config 2>/dev/null || echo "Not found")
- Key Auth: $(grep '^PubkeyAuthentication' /etc/ssh/sshd_config 2>/dev/null || echo "Not found")
- Max Auth Tries: $(grep '^MaxAuthTries' /etc/ssh/sshd_config 2>/dev/null || echo "Not found")

Host Keys:
$(ls -la /etc/ssh/ssh_host_*_key.pub 2>/dev/null || echo "No host keys found")

Firewall Status:
$(command -v ufw >/dev/null && ufw status verbose || echo "UFW not found")

Fail2ban Status:
$(command -v fail2ban-client >/dev/null && fail2ban-client status sshd 2>/dev/null || echo "Fail2ban not found")

=== Security Features Applied ===
✓ SSH daemon hardened with secure configuration
✓ Host keys regenerated with strong algorithms
✓ Fail2ban installed and configured
✓ UFW firewall configured with SSH restrictions
✓ Security monitoring script created and scheduled
✓ SSH banner configured

=== End of Report ===
EOF

    chmod 600 "$REPORT_FILE" 2>/dev/null || true
    echo -e "${GREEN}Audit report created: $REPORT_FILE${NC}"
}

# Main execution
main() {
    echo -e "${BLUE}Starting improved SSH hardening process...${NC}"

    # Update package lists
    echo -e "${YELLOW}Updating package lists...${NC}"
    DEBIAN_FRONTEND=noninteractive apt-get update

    apply_ssh_hardening
    create_ssh_banner
    secure_host_keys
    configure_fail2ban
    configure_firewall
    create_monitoring_script

    if test_ssh_config; then
        if restart_ssh_service; then
            create_audit_report

            echo -e "${GREEN}=== SSH Hardening Complete ===${NC}"
            echo -e "${GREEN}Server $(hostname) has been successfully hardened${NC}"
            echo -e "${YELLOW}IMPORTANT: Ensure you have SSH keys set up before disabling password authentication${NC}"
            echo -e "${YELLOW}Test your SSH connection before closing this session${NC}"

            # Display important information
            echo -e "\n${BLUE}=== Next Steps ===${NC}"
            echo -e "1. Test SSH connection from another terminal"
            echo -e "2. Verify fail2ban status: fail2ban-client status"
            echo -e "3. Check firewall status: ufw status verbose"
            echo -e "4. Review audit report: cat $REPORT_FILE"

        else
            echo -e "${RED}SSH service restart failed. Checking configuration...${NC}"
            exit 1
        fi
    else
        echo -e "${RED}SSH configuration test failed. Rolling back...${NC}"
        if [ -f /etc/ssh/sshd_config.backup.* ]; then
            cp /etc/ssh/sshd_config.backup.* /etc/ssh/sshd_config
            SSH_SERVICE=$(detect_ssh_service)
            systemctl restart "$SSH_SERVICE" 2>/dev/null || true
        fi
        exit 1
    fi
}

# Run main function
main "$@"