#!/bin/bash

# SSH Security Hardening Script
# Comprehensive hardening for all servers in the network

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging
LOG_FILE="/var/log/ssh_hardening_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$LOG_FILE")
exec 2>&1

echo -e "${BLUE}=== SSH Security Hardening Script ===${NC}"
echo -e "${BLUE}Started at: $(date)${NC}"
echo -e "${BLUE}Log file: $LOG_FILE${NC}"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}This script must be run as root${NC}"
   exit 1
fi

# Backup original SSH config
echo -e "${YELLOW}Creating backup of original SSH configuration...${NC}"
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d_%H%M%S)

# Function to apply SSH hardening rules
apply_ssh_hardening() {
    echo -e "${GREEN}Applying SSH hardening rules...${NC}"

    # Create hardened SSH config
    cat > /etc/ssh/sshd_config << 'EOF'
# SSH Hardening Configuration
# Generated by SSH Security Hardening Script

# Basic SSH Settings
Port 22
Protocol 2

# Authentication Security
PermitRootLogin no
PermitEmptyPasswords no
PasswordAuthentication yes  # Will be disabled after key setup
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys

# Security Settings
MaxAuthTries 3
MaxSessions 10
LoginGraceTime 60
ClientAliveInterval 300
ClientAliveCountMax 2
Banner /etc/ssh/banner

# Cryptographic Settings
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssl.com,aes256-gcm@openssl.com,aes128-gcm@openssl.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512

# Logging
LogLevel VERBOSE
SyslogFacility AUTH

# Access Control
AllowTcpForwarding no
X11Forwarding no
AllowAgentForwarding no
PermitTunnel no
PermitOpen none

# Subsystem Configuration
Subsystem sftp /usr/lib/openssh/sftp-server

# UsePAM
UsePAM yes

# Security Enhancements
StrictModes yes
UsePrivilegeSeparation yes
Compression no
TCPKeepAlive yes
UseDNS no

# IP-based restrictions (will be customized per server)
# AllowUsers specific_users
# AllowGroups specific_groups
# DenyUsers unwanted_users
# DenyGroups unwanted_groups
EOF

    chmod 644 /etc/ssh/sshd_config
    chown root:root /etc/ssh/sshd_config
}

# Function to create SSH banner
create_ssh_banner() {
    echo -e "${GREEN}Creating SSH banner...${NC}"

    cat > /etc/ssh/banner << 'EOF'
***************************************************************************
                            AUTHORIZED ACCESS ONLY
***************************************************************************

This system is for authorized users only. Individual use of this system
and/or network without authority from the system owner is strictly
prohibited.

Unauthorized access is a violation of state and federal, civil and criminal
laws. All activities on this system are monitored and logged.

***************************************************************************
                IMMEDIATE NOTIFICATION WILL BE SENT TO
              SYSTEM ADMINISTRATORS FOR VIOLATIONS
***************************************************************************
EOF

    chmod 644 /etc/ssh/banner
    chown root:root /etc/ssh/banner
}

# Function to secure SSH host keys
secure_host_keys() {
    echo -e "${GREEN}Securing SSH host keys...${NC}"

    # Regenerate host keys with stronger algorithms
    rm -f /etc/ssh/ssh_host_*_key*

    ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" -C "$(hostname)-ed25519"
    ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N "" -C "$(hostname)-rsa"
    ssh-keygen -t ecdsa -b 521 -f /etc/ssh/ssh_host_ecdsa_key -N "" -C "$(hostname)-ecdsa"

    chmod 600 /etc/ssh/ssh_host_*_key
    chmod 644 /etc/ssh/ssh_host_*_key.pub
    chown root:root /etc/ssh/ssh_host_*
}

# Function to configure fail2ban
configure_fail2ban() {
    echo -e "${GREEN}Configuring fail2ban for SSH...${NC}"

    # Install fail2ban if not present
    if ! command -v fail2ban-server &> /dev/null; then
        echo -e "${YELLOW}Installing fail2ban...${NC}"
        apt-get update
        apt-get install -y fail2ban
    fi

    # Create fail2ban SSH configuration
    cat > /etc/fail2ban/jail.local << 'EOF'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3
backend = systemd

[sshd]
enabled = true
port = 22
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
EOF

    systemctl restart fail2ban
    systemctl enable fail2ban
}

# Function to configure UFW firewall
configure_ufw() {
    echo -e "${GREEN}Configuring UFW firewall...${NC}"

    # Reset UFW
    ufw --force reset

    # Default policies
    ufw default deny incoming
    ufw default allow outgoing

    # Allow SSH from specific subnets (customize as needed)
    ufw allow from 192.168.1.0/24 to any port 22
    ufw allow from 10.0.0.0/8 to any port 22

    # Enable UFW
    ufw --force enable
}

# Function to create security monitoring script
create_monitoring_script() {
    echo -e "${GREEN}Creating security monitoring script...${NC}"

    cat > /usr/local/bin/ssh_security_monitor.sh << 'EOF'
#!/bin/bash

# SSH Security Monitoring Script
# Monitors SSH access and sends alerts

LOG_FILE="/var/log/auth.log"
ALERT_THRESHOLD=5
TIME_WINDOW=300  # 5 minutes

# Count failed SSH attempts in the time window
FAILED_ATTEMPTS=$(journalctl -u ssh --since "5 minutes ago" | grep -c "Failed password")

if [ "$FAILED_ATTEMPTS" -ge "$ALERT_THRESHOLD" ]; then
    echo "SECURITY ALERT: $FAILED_ATTEMPTS failed SSH attempts detected in the last 5 minutes" | \
    logger -t SSH_SECURITY_MONITOR -p auth.warning
fi

# Check for root login attempts
ROOT_ATTEMPTS=$(journalctl -u ssh --since "5 minutes ago" | grep -c "root.*Accepted")
if [ "$ROOT_ATTEMPTS" -gt 0 ]; then
    echo "SECURITY ALERT: Root login attempt detected" | \
    logger -t SSH_SECURITY_MONITOR -p auth.warning
fi
EOF

    chmod +x /usr/local/bin/ssh_security_monitor.sh

    # Add to crontab
    (crontab -l 2>/dev/null; echo "*/5 * * * * /usr/local/bin/ssh_security_monitor.sh") | crontab -
}

# Function to test SSH configuration
test_ssh_config() {
    echo -e "${GREEN}Testing SSH configuration...${NC}"

    if sshd -t; then
        echo -e "${GREEN}SSH configuration test passed${NC}"
        return 0
    else
        echo -e "${RED}SSH configuration test failed${NC}"
        return 1
    fi
}

# Function to restart SSH service
restart_ssh_service() {
    echo -e "${GREEN}Restarting SSH service...${NC}"
    systemctl restart sshd

    if systemctl is-active --quiet sshd; then
        echo -e "${GREEN}SSH service restarted successfully${NC}"
    else
        echo -e "${RED}Failed to restart SSH service${NC}"
        exit 1
    fi
}

# Function to create security audit report
create_audit_report() {
    echo -e "${GREEN}Creating security audit report...${NC}"

    REPORT_FILE="/var/log/ssh_security_audit_$(date +%Y%m%d_%H%M%S).txt"

    cat > "$REPORT_FILE" << EOF
=== SSH Security Audit Report ===
Server: $(hostname)
Date: $(date)
IP Address: $(hostname -I | awk '{print $1}')

SSH Configuration:
- Protocol: $(grep '^Protocol' /etc/ssh/sshd_config)
- Port: $(grep '^Port' /etc/ssh/sshd_config)
- Root Login: $(grep '^PermitRootLogin' /etc/ssh/sshd_config)
- Password Auth: $(grep '^PasswordAuthentication' /etc/ssh/sshd_config)
- Key Auth: $(grep '^PubkeyAuthentication' /etc/ssh/sshd_config)
- Max Auth Tries: $(grep '^MaxAuthTries' /etc/ssh/sshd_config)

Host Keys:
$(ls -la /etc/ssh/ssh_host_*_key.pub)

Firewall Status:
$(ufw status verbose)

Fail2ban Status:
$(fail2ban-client status sshd)

Recent SSH Activity:
$(journalctl -u ssh --since "1 hour ago" | tail -20)

=== End of Report ===
EOF

    chmod 600 "$REPORT_FILE"
    echo -e "${GREEN}Audit report created: $REPORT_FILE${NC}"
}

# Main execution
main() {
    echo -e "${BLUE}Starting SSH hardening process...${NC}"

    apply_ssh_hardening
    create_ssh_banner
    secure_host_keys
    configure_fail2ban
    configure_ufw
    create_monitoring_script

    if test_ssh_config; then
        restart_ssh_service
        create_audit_report

        echo -e "${GREEN}=== SSH Hardening Complete ===${NC}"
        echo -e "${GREEN}Server $(hostname) has been successfully hardened${NC}"
        echo -e "${YELLOW}IMPORTANT: Ensure you have SSH keys set up before disabling password authentication${NC}"
        echo -e "${YELLOW}Test your SSH connection before closing this session${NC}"

        # Display important information
        echo -e "\n${BLUE}=== Next Steps ===${NC}"
        echo -e "1. Test SSH connection: ssh $(whoami)@$(hostname -I | awk '{print $1}')"
        echo -e "2. Verify fail2ban status: fail2ban-client status"
        echo -e "3. Check firewall status: ufw status verbose"
        echo -e "4. Review audit report: cat $REPORT_FILE"

    else
        echo -e "${RED}SSH configuration test failed. Rolling back...${NC}"
        cp /etc/ssh/sshd_config.backup.* /etc/ssh/sshd_config
        systemctl restart sshd
        exit 1
    fi
}

# Run main function
main "$@"